import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"

import Main from "../components/Main"
import About from "../components/About"
import Skills from "../components/Skills"
import Web3 from "../components/Web3"

import Contact from "../components/Contact"

export default function Home() {
  return (
    <>
      <Head>
        <title>Gopinho - Dev Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <Skills />
      <Web3 />
      <Contact />
    </>
  )
}
